import { NgModule } from '@angular/core';
import { MatButtonModule,
        MatToolbarModule,
        MatProgressSpinnerModule,
        MatInputModule,
        MatDialogModule,
        MatIconModule,
        MatCardModule,
        MatDatepickerModule,
        MatTableModule,
        MatPaginatorModule,
        MatSidenavModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatNativeDateModule,
        MatMenuModule,
        MatTooltipModule } from '@angular/material';

@NgModule({
    imports: [
        MatButtonModule,
        MatToolbarModule,
        MatProgressSpinnerModule,
        MatInputModule,
        MatIconModule,
        MatCardModule,
        MatDatepickerModule,
        MatTableModule,
        MatSidenavModule,
        MatPaginatorModule,
        MatFormFieldModule,
        MatDialogModule,
        MatExpansionModule,
        MatSnackBarModule,
        MatNativeDateModule,
        MatMenuModule,
        MatTooltipModule
    ],
    exports: [
        MatButtonModule,
        MatToolbarModule,
        MatProgressSpinnerModule,
        MatInputModule,
        MatIconModule,
        MatDialogModule,
        MatCardModule,
        MatPaginatorModule,
        MatDatepickerModule,
        MatTableModule,
        MatSnackBarModule,
        MatSidenavModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatNativeDateModule,
        MatMenuModule,
        MatTooltipModule
    ]
})
export class MaterialsComponent {}
